#!/usr/bin/env python3
"""Build a probe config YAML with explicit pairs from sampled_frames.yaml.

sampled_frames.yaml groups sampled (episode, frame) frames into categories:
``not_grasped``, ``water`` (bottle is heavy -> placed far) and ``no_water``
(bottle is light -> placed near). The counterfactual pairs pair the i-th
``water`` sample with the i-th ``no_water`` sample:

    pair i: full=<water[i]>  empty=<no_water[i]>

Usage:

    python scripts/build_counterfactual_config.py \
        --samples sampled_frames.yaml \
        --output configs/probes/water_weight_counterfactual.yaml \
        --config-name pi05_base_bi_flexiv_bottle_sorting_0817_fastvit_h100 \
        --checkpoint-dir checkpoints/.../39999
"""

from __future__ import annotations

import argparse
import pathlib

import yaml


def load_samples(path: pathlib.Path) -> dict:
    with open(path, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    categories = data.get("categories")
    if not isinstance(categories, dict):
        raise ValueError(f"{path}: missing 'categories' mapping")
    for name in ("water", "no_water"):
        if name not in categories:
            raise ValueError(f"{path}: categories missing '{name}'")
    return data


def build_pairs(samples: dict, limit: int | None) -> list[dict]:
    water = samples["categories"]["water"]["samples"]
    no_water = samples["categories"]["no_water"]["samples"]
    if limit is not None:
        water = water[:limit]
        no_water = no_water[:limit]
    if len(water) != len(no_water):
        raise ValueError(
            f"water ({len(water)}) and no_water ({len(no_water)}) sample counts differ; cannot pair them 1:1."
        )
    pairs = []
    for i, (full, empty) in enumerate(zip(water, no_water)):
        pairs.append(
            {
                "pair_id": i,
                "full": {"episode_index": full["episode"], "frame_index": full["frame"]},
                "empty": {"episode_index": empty["episode"], "frame_index": empty["frame"]},
            }
        )
    return pairs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--samples", default="sampled_frames.yaml")
    parser.add_argument("--output", required=True)
    parser.add_argument("--config-name", default=None, help="TrainConfig name (model.config_name)")
    parser.add_argument("--checkpoint-dir", required=True)
    parser.add_argument("--repo-id", default=None, help="Override dataset repo id")
    parser.add_argument("--limit", type=int, default=None, help="Only pair the first N samples")
    parser.add_argument("--num-steps", type=int, default=10)
    parser.add_argument("--base-seed", type=int, default=12345)
    parser.add_argument("--output-dir", default="outputs/tactile_counterfactual")
    parser.add_argument("--inference-mode", default="rtc", choices=["standard", "rtc"])
    args = parser.parse_args()

    samples = load_samples(pathlib.Path(args.samples))
    pairs = build_pairs(samples, args.limit)
    seed = samples.get("seed")

    model: dict = {"checkpoint_dir": args.checkpoint_dir}
    if args.config_name:
        model["config_name"] = args.config_name
    else:
        raise ValueError("--config-name is required (inline model configs are not generated by this script)")

    dataset: dict = {"repo_id": args.repo_id or samples.get("dataset"), "revision": None, "root": None}

    config = {
        "dataset": dataset,
        "model": model,
        "experiment": {
            "inference_mode": args.inference_mode,
            "num_steps": args.num_steps,
            "base_seed": args.base_seed,
            "batch_size": 1,
        },
        "output": {
            "dir": args.output_dir,
            "shard_size": 50,
            "save_fastvit_features": True,
            "save_tactile_tokens": True,
            "save_suffix_tokens": False,
            "save_adarms_cond": True,
            "save_action_hidden": True,
            "save_v_t": True,
            "save_x_t": True,
            "hidden_storage_dtype": "float16",
        },
        "pairs": pairs,
    }

    out = pathlib.Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        yaml.safe_dump(config, sort_keys=False, width=120),
        encoding="utf-8",
    )
    print(f"Wrote {len(pairs)} pairs to {out} (sampling seed from sampled_frames.yaml: {seed})")


if __name__ == "__main__":
    main()
